import java.util.ArrayList;

public class SubSet {
    public static void main(String[] args){
        subset("","abc");
        ArrayList<String> list= subsetList("","abc");
        System.out.println(list);

    }
    static void subset(String p,String up){
        if(up.isEmpty()){
           System.out.println(p);
           return;
        }
        subset(p+up.charAt(0),up.substring(1));
        subset(p,up.substring(1));

    }
    
   /**
 * This method generates all possible subsets of a given string using recursion.
 * It returns an ArrayList containing all subsets of the string formed by 
 * combining characters from the input.
 *
 * @param p  The "processed" part of the string. Initially, this is an empty string,
 *           and it accumulates characters as we include them in the subset.
 * @param up The "unprocessed" part of the string. This is the remaining part of the 
 *           string yet to be processed.
 * 
 * @return   An ArrayList<String> containing all subsets of the input string.
 *
 * Key Points:
 * - Base case: When the unprocessed string (`up`) is empty, we add the current 
 *   "processed" string (`p`) to the list and return it.
 * - Recursive calls:
 *   1. Include the first character of `up` in the subset and proceed with the rest 
 *      of the string (`p + up.charAt(0)` and `up.substring(1)`).
 *   2. Exclude the first character of `up` and proceed with the rest of the string 
 *      (`p` and `up.substring(1)`).
 * - Finally, combine the subsets generated by including and excluding the character.
 */
static ArrayList<String> subsetList(String p, String up) {
    if (up.isEmpty()) {
        ArrayList<String> list = new ArrayList<>();
        list.add(p); // Base case: Add the processed string to the list
        return list;/**This will returns a list with the subset of a string. It will return subset added to list. This list is then stored by either left or right */
    }
    // Recursive case: Include the first character in the subset
    ArrayList<String> left = subsetList(p + up.charAt(0), up.substring(1));
    // Recursive case: Exclude the first character from the subset
    ArrayList<String> right = subsetList(p, up.substring(1));
    // Combine both subsets and return
    left.addAll(right);
    return left;
}


 

    
}
